project_id = "fer-e-gabi"

[auth]
site_url = "https://fernandogreca.github.io/fer-e-gabi/"
additional_redirect_urls = ["http://localhost:3000/fer-e-gabi/"]
enable_signup = false
enable_anonymous_sign_ins = false
